Repository prgithubschool/day-1-caption-this, pull requests merged in 2024-10, with the labels that each got.

#26 Add caption alexr1210
  _slides/17-alexr1210.md
  _slides/alexr1210.md
Labels: REBECCA'S_TORMENT

#8 Pull me
  _slides/23-excursion-mwstewart.md
Labels: Training

#18 updating caption
  _slides/28-prakashsonani.md
Labels: documentation

#17 Added caption
  _slides/03-Bradfordio.md
Labels: RODNEY

#14 updating caption in line 6
  _slides/27-netxrunna.md
Labels: documentation

#11 updating my caption for conorrlewis
  _slides/04-conorrlewis.md
Labels: good first issue

#25 Add caption dbbloke
  _slides/05-dbbloke.md
Labels: THIS_TIME_NEXT_YEAR_WE'LL_BE_MILLIONAIRES

#27 Add caption suresh609
  _slides/31-suresh609.md
Labels: documentation
